// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kexwiwqgezjsfeklytiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtleHdpd3FnZXpqc2Zla2x5dGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5NTQwMDgsImV4cCI6MjA0OTUzMDAwOH0.UwTcAy2SXIJj2UQIyft_20Ycksb9_JWUUGFk1Jzh2sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);